{% set name = "deepdiff" %}
{% set version = "8.5.0" %}
{% set sha256 = "a4dd3529fa8d4cd5b9cbb6e3ea9c95997eaa919ba37dac3966c1b8f872dc1cd1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:  # [win]
    - patches/0001-Fix-encoding-error-on-Windows.patch  # [win]

build:
  number: 0
  # orjson is not available on s390x
  skip: true  # [py<37 or s390x]
  entry_points:
    - deep = deepdiff.commands:cli
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - m2-patch  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools
    - flit-core >=3.11,<4
  run:
    - orderly-set >=5.4.1,<6
    - orjson
    - python

test:
  source_files:
    - tests
    - conftest.py
  requires:
    - pip
    - pytest
    - click
    - numpy
    - pyyaml
    - python-dateutil
    - pydantic
    - tomli-w
    - pytz
    - pandas
  commands:
    - pip check
    # Skip tests known to fail: https://github.com/seperman/deepdiff/issues/323
    - pytest -v tests -k "not (test_serialization_text or test_deserialization or test_serialization_tree or test_deserialization_tree or test_delta_dump_and_read3 or delta_numpy7_arrays_of_different_sizes or test_polars or test_lfu)"
  imports:
    - deepdiff

about:
  home: https://github.com/seperman/deepdiff
  summary: Deep Difference and Search of any Python object/data.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Deep Difference of dictionaries, iterables, strings and other objects. 
    It will recursively look for all the changes.
  doc_url: https://deepdiff.readthedocs.io
  dev_url: https://github.com/seperman/deepdiff

extra:
  recipe-maintainers:
    - loriab
    - seperman
    - synapticarbors
