{% set name = "deepdiff" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 260c16f052d4badbf60351b4f77e8390bee03a0b516246f6839bc813fb429ddf
  patches:  # [win]
    - patches/0001-Fix-encoding-error-on-Windows.patch  # [win]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - deep = deepdiff.commands:cli
  skip: true  # [py<37]

requirements:
  build:
    - msys2-patch  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - ordered-set >=4.1.0,<4.2.0
    - orjson
    - python

test:
  source_files:
    - tests
    - conftest.py
  imports:
    - deepdiff
  commands:
    - pip check
    # Skip tests known to fail: https://github.com/seperman/deepdiff/issues/323
    - pytest -v tests -k "not (test_serialization_text or test_deserialization or test_serialization_tree or test_deserialization_tree or test_delta_dump_and_read3 or delta_numpy7_arrays_of_different_sizes or test_diff_command)"
  requires:
    - pip
    - pytest
    - click
    - numpy
    - pyyaml
    - python-dateutil
    - pydantic
    - tomli-w

about:
  home: https://github.com/seperman/deepdiff
  summary: Deep Difference and Search of any Python object/data.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Deep Difference of dictionaries, iterables, strings and other objects. 
    It will recursively look for all the changes.
  doc_url: https://deepdiff.readthedocs.io
  dev_url: https://github.com/seperman/deepdiff

extra:
  recipe-maintainers:
    - loriab
    - seperman
    - synapticarbors
  skip-lints:
    - patch_unnecessary
