travis:
  secure:
    BINSTAR_TOKEN: QygZbzz872KBz5CW3EPOXS6SXJ+TdY6jZge/ktu+QKqSgevlQVO6WOaPEUr8dC1fgE46NIxOdb/Np/GXH+2cVIUTaGYnPW/7Md86/movdBrBTeVS7TYjaRTt5/YPLVaTc8X8Cl/oHdHX5rjJhLkk+Zsq2qd9lyr7F3HtDduy84niKO+ky3ms8kYvZ11rCYtdMEUnoDML7XH/IMjb+OrrOMXcZYtuoBf7I4Cx/aKbdAcXrVcmRTIdej0SDCXLTJfnsT9hLgRW4UpYd/9ony4urVbeRSpPNeIO9M2MGmObrYcHc9UzERGmO0RLkajHQv8K2plY8iilG8dqodsYYhzhhloD2UQow2mVW/+lvxV2wtcJwLQubo1cH0bGXRfuwfUBGkecE3Etp9QXgJUo8KKfOGREz4KEbbqyxJyRxqLTaRSqiA/ZtanWCUn0moWltWUeKgmZf06mzsMZqg9UJ7Y50zvIsTdgDGexc1YRwWSyGjC/Xctb5D1zE3aZAHmi6aQUBGfwxTHTBiOwj/Ig9qMimqF4tJ2qE5ql4aH7LJQKaVL3XE3+ofvUUMA2TI6YzdaX0t5cEFxxZnjvS7o7aOakP7FpRXda9I3KY7Mq4/wiB0yVvMK05ckNqhabQ06RxGoVLXoid3Dx3q05mBYd/FcnuIvYuYzZPyO4dvVoPNkxqRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
