travis:
  secure:
    BINSTAR_TOKEN: vgsT5Fpsn95LzND7PGnGDIoDpj91o8skcM9eKVboV0axr3hBrBKMfCLvJolcXwcaTB2tLIYHJiES491U1ALxHxLrMcePAS0ynvuN9WB3xVsmlQxzE5j6lSYL3KjRcik/xeyN1suDUj4b5OS/BvWYF4EU+/6KAZMhbnEORE7YoqVCgfr5g0zTDcJtfgQCscfZaAp5NZgROy7SJ5MpOHJdO/Pfoc6oZtr0hAy9vXPAdhM8f19RkdFYc/4hD+FOgmUyn4oZKB/T6ddkICUz4Ug7lZbqxCce354IDrgmbpSx/1ZNLF5aoT9+0OiDpJ8B2Joy3lbdZ6Ff4j+IKKPRhEWwdXweSCdiGrtbnl4uh+LkPkPjGtub7Wc5tbxu9Hwdn+sGkKZnYz1BXFs7vPSQvgqxhv3J95POPZIVn30xH/ZQl7tLr/dMcbsbo+eYkiLBeiJ2xY44QRXcz+EXtdD9JxVGhHhZzMwAZfMU4wJ/FuWutQbm0ydNHGKZYPLlpstA3dlbCTw6cwjeFYvEoFBAQHqyUJrMO0JarwT5Vi/cUjrd9EEZHQ9tca0qn9BTEmhcfUKltM+rXmUgpelJFM/aQhqA33GaXLIWqhRocl4va0/4ARP8EW3O5A+C6sW0nhokE2hP9uX0Z5/KcMzIcCp12gbhYpp6z0SCyYWdYEe8rL2RdLE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
